GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/67e6af3167057c4e06f396d0

###
DELETE http://localhost:3001/api/notes/6853fa282dbeb8b3296a2a71

###
POST http://localhost:3001/api/notes 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY4MDI0YzAyMTcxNjEzMzBlZDBjMzJkYyIsImlhdCI6MTc1MDE4NDA3NywiZXhwIjoxNzUwMTg3Njc3fQ.JgbR4JrrNFr0jBg55ycVtTDx7z6DA5U8OlWzyPIdo50

{
    "content": "What's-a going wrong?",
    "important": false,
    "userId" : "68024c0217161330ed0c32dc"
}

###
PUT http://localhost:3001/api/notes/67ed197b41e28d66af456047
Content-Type: application/json

{
    "content": "VS code rest client is overrated IMO",
    "important": true
}

### SAD PATH
### find a non-existent ID
GET http://localhost:3001/api/notes/67e6af3167057c4e06f396d1

### find a wrongly formatted ID
GET http://localhost:3001/api/notes/12

### Nonsense request
HEAD  http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/notes 
Content-Type: application/json

{
    "content": "Å",
    "important": false
}
