# Happy path testing
### Home page
GET http://localhost:3001/info

### Get all
GET http://localhost:3001/api/persons/

### Find a real ID
GET http://localhost:3001/api/persons/67ec008578ada503ecd66b47

### Delete
DELETE  http://localhost:3001/api/persons/67ed1e37d258b7c5fb93f15c

### Post
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Bobby bobbert", 
    "number": "12-34456789"
}

### Put
PUT http://localhost:3001/api/persons/67ee857a1e29f32b942e95c8
content-type: application/json

{ 
    "name": "Robby Robbert", 
    "number": "98-7654321"
}

# Unhappy path testing
### Find a non-existent ID
GET http://localhost:3001/api/persons/67ec008578ada503ecd66b44

### Find a wrongly-formatted ID
GET http://localhost:3001/api/persons/12

### Post an incomplete person (no number)
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Bobby bobbert"
}
### Post an incomplete person (no name)
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "number": "123-4456789"
}

### Post too short a name
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Å", 
    "number": "123-4456789"
}
### Put too short a name
PUT http://localhost:3001/api/persons/67ee8a4ef607642eda6a264b
content-type: application/json

{ 
    "name": "B", 
    "number": "987-654321"
}

### Put an invalid phone number
POST http://localhost:3001/api/persons/
content-type: application/json

{ 
    "name": "Bklasjdhfjkl", 
    "number": "98-765-432-1"
}



### Delete faulty crap
DELETE  http://localhost:3001/api/persons/67ee857a1e29f32b942e95c8