# Happy path testing
### Get all
GET http://localhost:3003/api/blogs

### Post
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RTdXBlclVzZXIiLCJpZCI6IjY4MTM3OWNmMzhkYmE4OTRkNzRiODM5OSIsImlhdCI6MTc1MTI3OTc5NCwiZXhwIjoxNzUxMjgzMzk0fQ.Vl2mNLjsp3ai3iBREj0wsOimtOZPCvw7kFIwGaMfLMo

{
    "title": "Mental Health Fridays: Blurring out the stigma",
    "author": "Ameena k.g ",
    "url": "https://randomsbyarandom.wordpress.com/2015/08/16/mental-health-fridays-blurring-out-the-stigma/",
    "likes": 90
}

### Put
PUT http://localhost:3003/api/blogs/68626cc29783ee025c055924
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RTdXBlclVzZXIiLCJpZCI6IjY4MTM3OWNmMzhkYmE4OTRkNzRiODM5OSIsImlhdCI6MTc1MTI5MzAyMSwiZXhwIjoxNzUxMjk2NjIxfQ.N1Eo9k4827UpWl6uAeyKi3qQLGGhBwfNm4faR9papvo

{
    "title": "5.8",
    "author": "The request file ",
    "url": "My local VScode",
    "likes": 12
}

### Delete
DELETE http://localhost:3003/api/blogs/6865307f88ee8f8f15753f2d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RTdXBlclVzZXIiLCJpZCI6IjY4NjUzMDc5NzYwZmIzMTUyYzIyMDdlYiIsImlhdCI6MTc1MTg4OTg4MSwiZXhwIjoxNzUxODkzNDgxfQ.17OHT8d5i3JNWq1DmMEffkXV1PxGAwpr5gR46TB8hfI